import Head from "next/head";
import { useRouter } from "next/router";

import { Flex, Button, Text, HStack } from "@chakra-ui/react";
import Layout from "@/layouts/layout";

export default function Home() {
  const router = useRouter();

  const login = () => {
    router.push("/auth/login");
  };

  const signUp = () => {
    router.push("/auth/signup");
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <Flex
            direction="column"
            w="100%"
            h="100%"
            justify="center"
            align="center"
          >
            <Text color="gray.400">Hello, login or sign up to continue.</Text>

            <HStack mt="12px" spacing="32px">
              <Button {...styles.buttonProps} onClick={login}>
                Login
              </Button>
              <Button {...styles.buttonProps} onClick={signUp}>
                Sign up
              </Button>
            </HStack>
          </Flex>
        </Layout>
      </main>
    </>
  );
}

const styles = {
  buttonProps: {
    bg: "gray.800",
    color: "gray.200",
    _hover: {
      bg: "gray.700",
    },
  },
};
